FROM caddy:2.11.3-alpine

WORKDIR /app

RUN addgroup -S caddy && adduser -S caddy -G caddy -D
RUN mkdir -p /etc/caddy && chown -R caddy:caddy /app

EXPOSE 5000

USER caddy

# docker build -f ci/infra/Dockerfile.dev -t languify-server:latest .
# docker run -p 5000:5000 -v $(pwd)/dist/site:/app/site -v $(pwd)/ci/infra/Caddyfile:/app/Caddyfile --name languifyjs languify-server:latest
CMD ["caddy", "run", "--watch", "--config", "/app/Caddyfile", "--adapter", "caddyfile"]
